version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.5.1
    - 1.6.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: jbuilder
    versions:
    - 2.11.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: capybara
    versions:
    - 3.34.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
